// <auto-generated />
using EarthOnline.Desktop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EarthOnline.Desktop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001063147_AddDeletedAt")]
    partial class AddDeletedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EarthOnline.Desktop.Data.Entities.AchievementEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AutoKey")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "autoKey");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "desc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("manual")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<bool>("Unlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasAnnotation("Relational:JsonPropertyName", "unlocked");

                    b.Property<string>("UnlockedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "unlockedAt");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("EarthOnline.Desktop.Data.Entities.ActivityEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "kind");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("EarthOnline.Desktop.Data.Entities.BagCategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "scope");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "sortOrder");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "SortOrder");

                    b.ToTable("bag_categories", (string)null);
                });

            modelBuilder.Entity("EarthOnline.Desktop.Data.Entities.CollectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("FileMetaJson")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "fileMetaJson");

                    b.Property<string>("FileUri")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "fileUri");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "note");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("EarthOnline.Desktop.Data.Entities.ItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("physical")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("EarthOnline.Desktop.Data.Entities.LocationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "lat");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "note");

                    b.Property<string>("TagsJson")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "tagsJson");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("EarthOnline.Desktop.Data.Entities.MemoEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("note")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("memos", (string)null);
                });

            modelBuilder.Entity("EarthOnline.Desktop.Data.Entities.ProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<byte[]>("AvatarData")
                        .HasColumnType("BLOB")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarData");

                    b.Property<string>("AvatarKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarKey");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarPath");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasAnnotation("Relational:JsonPropertyName", "birthDate");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "country");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasAnnotation("Relational:JsonPropertyName", "customFieldsJson");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "province");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "signature");

                    b.HasKey("Id");

                    b.ToTable("profile", (string)null);
                });

            modelBuilder.Entity("EarthOnline.Desktop.Data.Entities.TaskEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("todo")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoneAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "doneAt");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "dueDate");

                    b.Property<string>("LastModified")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "lastModified");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "note");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order")
                        .HasAnnotation("Relational:JsonPropertyName", "order");

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "parentId");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "progress");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("planning")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Status");

                    b.ToTable("tasks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
